"""Deterministic stdlib fold of a ticket's full event log into a context dossier.

``derived/context/<KEY>.md`` is the fix for the architectural irony that the sole
source of truth is invisible to the agents it exists for: ``snapshot.fold``
discards answered-question text, phase-change reasons, and step summaries once
it has extracted the small bit of state it needs, so every one-step reconciler
session re-derives context from scratch. This module folds the *whole* log
(archive included) into a token-bounded, human/agent-readable Markdown file,
regenerated beside the snapshot on every append (see ``ops._append``) and read
by the reconcile skill's step 0.
"""
from __future__ import annotations

from pathlib import Path

from . import events as E
from . import event_log, store
from . import snapshot as snap_mod
from .dispatcher import parse_depends_on

_BANNER = (
    "<!-- GENERATED by maestro — DO NOT EDIT. Fold of events/<KEY>.jsonl (+ archive). -->"
)

# Per-section caps keep the dossier token-bounded regardless of ticket age —
# only the most recent N entries of each kind are shown, oldest-dropped-first.
MAX_PHASE_CHANGES = 15
MAX_ANSWERED_QUESTIONS = 15
MAX_FAILURES = 10
MAX_CI_OBSERVATIONS = 10
MAX_IMPL_STEPS = 15


def _tail(items: list, cap: int) -> tuple[list, int]:
    """Most recent `cap` items, plus how many older ones were dropped."""
    if len(items) <= cap:
        return items, 0
    return items[-cap:], len(items) - cap


def render(key: str, title: str | None, events: list[dict], dep_phases: dict[str, str]) -> str:
    """Pure fold: identical (key, title, events, dep_phases) -> byte-identical text."""
    asked: dict[str, str] = {}
    phase_changes: list[tuple[str, str, str]] = []
    answered: list[tuple[str, str, str, str]] = []
    failures: list[tuple[str, str]] = []
    ci_observed: list[tuple[str, str]] = []
    impl_steps: list[tuple[str, object, str, str, str, str]] = []

    for ev in events:
        t = ev.get("type")
        p = ev.get("payload") or {}
        ts = ev.get("ts", "")
        if t == E.QUESTION_ASKED:
            asked[p.get("qid", "")] = p.get("text", "")
        elif t == E.QUESTION_ANSWERED:
            qid = p.get("qid", "")
            answered.append((ts, qid, asked.get(qid, ""), p.get("answer", "")))
        elif t == E.PHASE_CHANGED:
            phase_changes.append((ts, p.get("phase", ""), p.get("reason", "")))
        elif t == E.FAILED:
            failures.append((ts, p.get("error", "")))
        elif t == E.CI_OBSERVED:
            ci_observed.append((ts, p.get("state", "")))
        elif t == E.IMPL_STEP:
            if p.get("summary"):
                impl_steps.append((ts, p.get("turn"), p.get("role", ""), p.get("kind", ""),
                                    p.get("tool", ""), p["summary"]))

    lines = [_BANNER, "", f"# Context: {key}" + (f" — {title}" if title else ""), ""]

    lines.append("## Phase history")
    shown, dropped = _tail(phase_changes, MAX_PHASE_CHANGES)
    if dropped:
        lines.append(f"_({dropped} earlier phase change(s) omitted)_")
    for ts, phase, reason in shown:
        lines.append(f"- {ts} → **{phase}**" + (f": {reason}" if reason else ""))
    if not phase_changes:
        lines.append("_none_")
    lines.append("")

    lines.append("## Answered questions")
    shown, dropped = _tail(answered, MAX_ANSWERED_QUESTIONS)
    if dropped:
        lines.append(f"_({dropped} earlier answer(s) omitted)_")
    for ts, qid, q, a in shown:
        lines.append(f"- {ts} `{qid}`")
        lines.append(f"  - Q: {q}")
        lines.append(f"  - A: {a}")
    if not answered:
        lines.append("_none_")
    lines.append("")

    lines.append("## Failures")
    shown, dropped = _tail(failures, MAX_FAILURES)
    if dropped:
        lines.append(f"_({dropped} earlier failure(s) omitted)_")
    for ts, err in shown:
        lines.append(f"- {ts}: {err}")
    if not failures:
        lines.append("_none_")
    lines.append("")

    lines.append("## CI observations")
    shown, dropped = _tail(ci_observed, MAX_CI_OBSERVATIONS)
    if dropped:
        lines.append(f"_({dropped} earlier observation(s) omitted)_")
    for ts, state in shown:
        lines.append(f"- {ts}: {state}")
    if not ci_observed:
        lines.append("_none_")
    lines.append("")

    lines.append("## Recent implementation steps")
    shown, dropped = _tail(impl_steps, MAX_IMPL_STEPS)
    if dropped:
        lines.append(f"_({dropped} earlier step(s) omitted)_")
    for ts, turn, role, kind, tool, summary in shown:
        prefix = f"turn {turn} [{role}]" if turn is not None else f"[{role}]"
        tool_suffix = f" ({tool})" if tool else ""
        lines.append(f"- {ts} {prefix} {kind}{tool_suffix}: {summary}")
    if not impl_steps:
        lines.append("_none_")
    lines.append("")

    lines.append("## Dependencies")
    if dep_phases:
        for dep_key in sorted(dep_phases):
            lines.append(f"- {dep_key}: {dep_phases[dep_key]}")
    else:
        lines.append("_none_")
    lines.append("")

    return "\n".join(lines) + "\n"


def context_path(home: Path, key: str) -> Path:
    return home / "derived" / "context" / f"{store.validate_key(key)}.md"


def regenerate(home: Path, key: str) -> Path:
    """Fold the full log (archive included) into the dossier and atomically
    persist it beside the snapshot. Called from ``ops._append`` so the dossier
    is always current after every event — no separate regeneration step.
    """
    events = event_log.read(home, key)
    spec_path = store.spec_path(home, key)
    spec_text = spec_path.read_text(encoding="utf-8") if spec_path.exists() else ""
    dep_phases = {dep: snap_mod.load(home, dep).phase for dep in parse_depends_on(spec_text)}
    title = next((e["payload"].get("title") for e in events if e.get("type") == E.TICKET_CREATED), None)
    text = render(key, title, events, dep_phases)
    path = context_path(home, key)
    store.atomic_write(path, text)
    return path
