"""Deterministic stdlib fold of a ticket's full event log into a context dossier.

``derived/context/<KEY>.md`` is the fix for the architectural irony that the sole
source of truth is invisible to the agents it exists for: ``snapshot.fold``
discards answered-question text, phase-change reasons, and step summaries once
it has extracted the small bit of state it needs, so every one-step reconciler
session re-derives context from scratch. This module folds the *whole* log
(archive included) into a token-bounded, human/agent-readable Markdown file,
regenerated beside the snapshot on every append (see ``ops._append``) and read
by the reconcile skill's step 0.
"""
from __future__ import annotations

from pathlib import Path

from . import events as E
from . import event_log, store
from . import locate as locate_mod
from . import repos as repos_mod
from . import snapshot as snap_mod
from .config import Config
from .dispatcher import parse_depends_on

_BANNER = (
    "<!-- GENERATED by maestro — DO NOT EDIT. Fold of events/<KEY>.jsonl (+ archive). -->"
)

# Per-section caps keep the dossier token-bounded regardless of ticket age —
# only the most recent N entries of each kind are shown, oldest-dropped-first.
MAX_PHASE_CHANGES = 15
MAX_ANSWERED_QUESTIONS = 15
MAX_FAILURES = 10
MAX_CI_OBSERVATIONS = 10
MAX_IMPL_STEPS = 15
MAX_LOCATE_HINTS = 15
MAX_SYMBOL_ROWS = 30
MAX_PRIOR_EDIT_FILES = 15


def _tail(items: list, cap: int) -> tuple[list, int]:
    """Most recent `cap` items, plus how many older ones were dropped."""
    if len(items) <= cap:
        return items, 0
    return items[-cap:], len(items) - cap


def render(key: str, title: str | None, events: list[dict], dep_phases: dict[str, str],
           locate: dict | None = None) -> str:
    """Pure fold: identical (key, title, events, dep_phases, locate) -> byte-identical
    text. *locate* is `None` (the default) unless the ticket's repo binding has
    `file_hints` on -- with it `None`, output is byte-identical to before T-124
    (`tests/test_context.py::test_render_is_byte_identical_for_the_same_events`)."""
    asked: dict[str, str] = {}
    phase_changes: list[tuple[str, str, str]] = []
    answered: list[tuple[str, str, str, str]] = []
    failures: list[tuple[str, str]] = []
    ci_observed: list[tuple[str, str, str]] = []
    impl_steps: list[tuple[str, object, str, str, str, str]] = []

    for ev in events:
        t = ev.get("type")
        p = ev.get("payload") or {}
        ts = ev.get("ts", "")
        if t == E.QUESTION_ASKED:
            asked[p.get("qid", "")] = p.get("text", "")
        elif t == E.QUESTION_ANSWERED:
            qid = p.get("qid", "")
            answered.append((ts, qid, asked.get(qid, ""), p.get("answer", "")))
        elif t == E.PHASE_CHANGED:
            phase_changes.append((ts, p.get("phase", ""), p.get("reason", "")))
        elif t == E.FAILED:
            failures.append((ts, p.get("error", "")))
        elif t == E.CI_OBSERVED:
            ci_observed.append((ts, p.get("state", ""), p.get("failure_excerpt", "")))
        elif t == E.IMPL_STEP:
            if p.get("summary"):
                impl_steps.append((ts, p.get("turn"), p.get("role", ""), p.get("kind", ""),
                                    p.get("tool", ""), p["summary"]))

    lines = [_BANNER, "", f"# Context: {key}" + (f" — {title}" if title else ""), ""]

    lines.append("## Phase history")
    shown, dropped = _tail(phase_changes, MAX_PHASE_CHANGES)
    if dropped:
        lines.append(f"_({dropped} earlier phase change(s) omitted)_")
    for ts, phase, reason in shown:
        lines.append(f"- {ts} → **{phase}**" + (f": {reason}" if reason else ""))
    if not phase_changes:
        lines.append("_none_")
    lines.append("")

    lines.append("## Answered questions")
    shown, dropped = _tail(answered, MAX_ANSWERED_QUESTIONS)
    if dropped:
        lines.append(f"_({dropped} earlier answer(s) omitted)_")
    for ts, qid, q, a in shown:
        lines.append(f"- {ts} `{qid}`")
        lines.append(f"  - Q: {q}")
        lines.append(f"  - A: {a}")
    if not answered:
        lines.append("_none_")
    lines.append("")

    lines.append("## Failures")
    shown, dropped = _tail(failures, MAX_FAILURES)
    if dropped:
        lines.append(f"_({dropped} earlier failure(s) omitted)_")
    for ts, err in shown:
        lines.append(f"- {ts}: {err}")
    if not failures:
        lines.append("_none_")
    lines.append("")

    lines.append("## CI observations")
    shown, dropped = _tail(ci_observed, MAX_CI_OBSERVATIONS)
    if dropped:
        lines.append(f"_({dropped} earlier observation(s) omitted)_")
    for ts, state, excerpt in shown:
        lines.append(f"- {ts}: {state}")
        if excerpt:
            lines.append(f"  ```\n  {excerpt}\n  ```")
    if not ci_observed:
        lines.append("_none_")
    lines.append("")

    lines.append("## Recent implementation steps")
    shown, dropped = _tail(impl_steps, MAX_IMPL_STEPS)
    if dropped:
        lines.append(f"_({dropped} earlier step(s) omitted)_")
    for ts, turn, role, kind, tool, summary in shown:
        prefix = f"turn {turn} [{role}]" if turn is not None else f"[{role}]"
        tool_suffix = f" ({tool})" if tool else ""
        lines.append(f"- {ts} {prefix} {kind}{tool_suffix}: {summary}")
    if not impl_steps:
        lines.append("_none_")
    lines.append("")

    lines.append("## Dependencies")
    if dep_phases:
        for dep_key in sorted(dep_phases):
            lines.append(f"- {dep_key}: {dep_phases[dep_key]}")
    else:
        lines.append("_none_")
    lines.append("")

    if locate:
        hints = locate.get("hints") or []
        lines.append("## Suggested starting points")
        shown, dropped = _tail(hints, MAX_LOCATE_HINTS)
        if dropped:
            lines.append(f"_({dropped} earlier hint(s) omitted)_")
        for h in shown:
            lines.append(f"- `{h['path']}` ({h['provenance']})")
        if not hints:
            lines.append("_none_")
        lines.append("")

        symbols = locate.get("symbols") or []
        lines.append("## Symbol map")
        shown, dropped = _tail(symbols, MAX_SYMBOL_ROWS)
        if dropped:
            lines.append(f"_({dropped} earlier symbol(s) omitted)_")
        for s in shown:
            doc_suffix = f" — {s['docstring']}" if s.get("docstring") else ""
            lines.append(
                f"- `{s['path']}:{s['line_start']}-{s['line_end']}` "
                f"{s['name']} ({s['kind']}){doc_suffix}")
        if not symbols:
            lines.append("_none_")
        lines.append("")

        prior = locate.get("prior_edits") or []
        lines.append("## Files edited in prior sessions")
        shown, dropped = _tail(prior, MAX_PRIOR_EDIT_FILES)
        if dropped:
            lines.append(f"_({dropped} earlier file(s) omitted)_")
        for f in shown:
            lines.append(f"- `{f}`")
        if not prior:
            lines.append("_none_")
        lines.append("")

    return "\n".join(lines) + "\n"


def context_path(home: Path, key: str) -> Path:
    return home / "derived" / "context" / f"{store.validate_key(key)}.md"


def regenerate(cfg: Config, key: str) -> Path:
    """Fold the full log (archive included) into the dossier and atomically
    persist it beside the snapshot. Called from ``ops._append`` so the dossier
    is always current after every event — no separate regeneration step.

    T-124: when *key*'s resolved repo binding has ``file_hints`` on, also folds
    in the cached (never recomputed here -- see ``ops.locate``/``maestro
    locate <KEY>``) locate hints; ships dark (``locate=None``, byte-identical
    output) for every binding that hasn't opted in.
    """
    home = cfg.home
    events = event_log.read(home, key)
    spec_path = store.spec_path(home, key)
    spec_text = spec_path.read_text(encoding="utf-8") if spec_path.exists() else ""
    dep_phases = {dep: snap_mod.load(home, dep).phase for dep in parse_depends_on(spec_text)}
    title = next((e["payload"].get("title") for e in events if e.get("type") == E.TICKET_CREATED), None)
    locate = None
    if repos_mod.resolve(cfg, home, key).file_hints:
        locate = locate_mod.load_cached(home, key)
    text = render(key, title, events, dep_phases, locate)
    path = context_path(home, key)
    store.atomic_write(path, text)
    return path
