"""Generate docs/state-machine.md and docs/dispatch-gates.md -- derived, never
retyped. Everything the two files describe is read straight off the running
source (``statemachine.TRANSITIONS``/``SLEEPING_PHASES``/``TERMINAL_PHASES``/
``ACTIVE_PHASES`` for the phase diagram; an AST walk of ``dispatcher.py`` for the
gate table), so the docs cannot drift from the code the way a hand-drawn diagram
would. Run via ``make diagram``; ``tests/test_diagram.py`` fails ``make test`` if
either committed file is stale.
"""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

from . import statemachine

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
STATE_DIAGRAM_PATH = DOCS_DIR / "state-machine.md"
DISPATCH_GATES_PATH = DOCS_DIR / "dispatch-gates.md"
DISPATCHER_SOURCE_PATH = REPO_ROOT / "maestro" / "dispatcher.py"

_HEADER = "<!-- GENERATED by `make diagram` (maestro/diagram.py) -- DO NOT EDIT. -->"


def _safe_id(phase_value: str) -> str:
    """Mermaid ``stateDiagram-v2`` state ids can't contain hyphens -- the
    parser tokenizes a bare hyphenated id as colliding with the ``-->``
    arrow (confirmed against the real mermaid parser: ``triaging -->
    awaiting-human`` fails with a 'Parse error ... Expecting SPACE, NL' on
    the second hyphen, and quoting the bare id in a transition doesn't fix
    it either). So every phase gets an underscore id here, aliased to its
    real, hyphenated name as a display label via `state "<name>" as <id>`."""
    return phase_value.replace("-", "_")


def render_state_diagram() -> str:
    """A mermaid ``stateDiagram-v2`` built solely from ``statemachine.py``'s
    ``TRANSITIONS``/``SLEEPING_PHASES``/``TERMINAL_PHASES``/``ACTIVE_PHASES``.
    Frozensets don't have a stable iteration order across interpreter runs
    (str hashing is salted per-process), so every set-derived line is sorted
    by phase value -- otherwise the drift-guard test would flap on hash seed
    alone, not on real drift."""
    lines = [_HEADER, "", "# maestro state machine", "",
              "Derived from `maestro/statemachine.py` (`TRANSITIONS`, `SLEEPING_PHASES`, "
              "`TERMINAL_PHASES`, `ACTIVE_PHASES`) -- regenerate with `make diagram` after "
              "touching that file; `tests/test_diagram.py` fails `make test` otherwise.",
              "", "```mermaid", "stateDiagram-v2"]
    for phase in statemachine.Phase:
        lines.append(f'    state "{phase.value}" as {_safe_id(phase.value)}')
    for phase in statemachine.Phase:
        for dst in sorted(statemachine.TRANSITIONS.get(phase, set()), key=lambda p: p.value):
            lines.append(f"    {_safe_id(phase.value)} --> {_safe_id(dst.value)}")
    lines += ["", "    classDef sleeping fill:#fff3cd,stroke:#997404",
              "    classDef terminal fill:#d1e7dd,stroke:#0f5132",
              "    classDef active fill:#cfe2ff,stroke:#084298"]
    for group, cls in ((statemachine.SLEEPING_PHASES, "sleeping"),
                        (statemachine.TERMINAL_PHASES, "terminal"),
                        (statemachine.ACTIVE_PHASES, "active")):
        names = " ".join(sorted(_safe_id(p.value) for p in group))
        if names:
            lines.append(f"    class {names} {cls}")
    lines += ["```", ""]
    return "\n".join(lines)


def _outcome_literals(value: ast.expr) -> list[tuple[int, str]]:
    """(lineno, literal) for every string literal an outcome-valued
    expression evaluates to: a plain string constant, or -- for the one
    ``<a> if <cond> else <b>`` site in ``dispatcher.py`` (the ``dry_run``
    branch of the missing-ACs gate) -- both arms, since either can be the
    outcome a real sweep assigns. Each pair's lineno is the literal's own
    (``ast.Constant.lineno``), not the enclosing assignment's -- the two can
    differ when the dict literal that holds it spans multiple lines, and a
    row pointing at the wrong line is worse than not generating one."""
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return [(value.lineno, value.value)]
    if isinstance(value, ast.IfExp):
        return _outcome_literals(value.body) + _outcome_literals(value.orelse)
    return []


def _dict_outcome_value(node: ast.Dict) -> ast.expr | None:
    """The value expression keyed ``"outcome"`` in a dict-literal AST node,
    or None if that dict has no such key (a plain ``decisions[key] = {...}``
    that isn't an outcome assignment at all)."""
    for k, v in zip(node.keys, node.values):
        if isinstance(k, ast.Constant) and k.value == "outcome":
            return v
    return None


def _outcome_assignments(source: str) -> list[tuple[int, str]]:
    """(lineno, literal) for every ``decisions[<key>]`` outcome assignment in
    `source` -- both the subscript form
    (``decisions[<key>]["outcome"] = "<literal>"``) and the dict-literal form
    (``decisions[<key>] = {"outcome": "<literal>", ...}``), the latter dropped
    by this walk until T-93 widened it. Either form's value may be a plain
    string or a conditional expression, in which case both arms are yielded
    (see `_outcome_literals`). Sorted into source order -- ``ast.walk`` visits
    nodes breadth-first, not in source order, so the sort is what actually
    orders these, not incidental."""
    tree = ast.parse(source)
    found: list[tuple[int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Subscript):
            continue
        value_expr: ast.expr | None
        if (isinstance(target.slice, ast.Constant) and target.slice.value == "outcome"
                and isinstance(target.value, ast.Subscript)
                and isinstance(target.value.value, ast.Name)
                and target.value.value.id == "decisions"):
            # decisions[<key>]["outcome"] = <value>
            value_expr = node.value
        elif (isinstance(target.value, ast.Name) and target.value.id == "decisions"
                and isinstance(node.value, ast.Dict)):
            # decisions[<key>] = {"outcome": <value>, ...}
            value_expr = _dict_outcome_value(node.value)
        else:
            value_expr = None
        if value_expr is None:
            continue
        found.extend(_outcome_literals(value_expr))
    found.sort(key=lambda pair: pair[0])
    return found


# T-93: the four sweep-level brakes that short-circuit the ENTIRE spawn phase
# before any per-key outcome above is assigned -- fleet pause exits before
# due-computation even runs (no `decisions[key]` entries at all that sweep);
# the other three run after due-computation (so due/claimed/etc outcomes from
# the loop above are still set) but skip every spawn-phase gate, so no key
# reaches `spawned`/`would_spawn` that sweep. (name, marker, description) --
# `marker` is matched as a literal substring of its defining source line, not
# a hardcoded line number, so `_brake_source_lines` can't go stale the way a
# retyped `:NNNN` would the next time `dispatch()` grows or shrinks above it.
_BRAKES: tuple[tuple[str, str, str], ...] = (
    ("fleet pause", "if fleet.pause_state(home, now) is not None:",
     "the board-wide kill switch (`maestro fleet pause`) -- ahead of "
     "everything else; mint/sync/worktrees/backup/sessions all stay "
     "untouched and due-computation never runs, so no `decisions[key]` "
     "entry is made at all this sweep"),
    ("rate-limit pause", "paused_until_ts = ratelimit.paused_until(home, now)",
     "a live 429 backoff window; while paused, nothing spawns and the spawn "
     "ledger is left untouched"),
    ("runaway auto-brake", "_maybe_trip_runaway_brake(cfg, home, now, health)",
     "GA-5's no-progress circuit breaker, armed off `derived/health.json`"),
    ("spend ceiling", "spend.over_ceiling(cfg, now)",
     "GA-11's daily spend ceiling, a pure read so it still applies under "
     "`dry_run`"),
)


def _brake_source_lines(source: str) -> list[tuple[str, int, str]]:
    """(name, lineno, description) for each of `_BRAKES`, located by finding
    its marker as a plain substring of a source line -- raises if a marker
    has drifted out of `dispatcher.py` entirely, so a rename there fails
    `make diagram`/`make test` loudly instead of silently going stale."""
    lines = source.splitlines()
    found = []
    for name, marker, desc in _BRAKES:
        lineno = next((i for i, line in enumerate(lines, start=1) if marker in line), None)
        if lineno is None:
            raise ValueError(f"dispatch gate brake marker not found in dispatcher.py: {marker!r}")
        found.append((name, lineno, desc))
    return found


def render_dispatch_gates() -> str:
    """The ordered dispatch gate table -- every outcome a sweep's `dispatch()`
    can write into `decisions[key]["outcome"]`, whether the source assigns it
    via ``decisions[key]["outcome"] = "<literal>"`` or a
    ``decisions[key] = {"outcome": "<literal>", ...}`` dict literal (a
    conditional-expression value contributes both its arms) -- AST-walked out
    of ``dispatcher.py`` in source order, plus the four sweep-level brakes
    that pre-empt the spawn phase entirely. The only artifact that describes
    the resource layer (throttle, repo caps, credentials, runner preflight,
    spend ceiling, ...) statically."""
    source = DISPATCHER_SOURCE_PATH.read_text()
    rows = _outcome_assignments(source)
    brakes = _brake_source_lines(source)
    lines = [_HEADER, "", "# dispatch gate table", "",
              "Every `decisions[key][\"outcome\"]` a sweep can assign -- via either "
              "`decisions[key][\"outcome\"] = \"<literal>\"` or a "
              "`decisions[key] = {\"outcome\": \"<literal>\", ...}` dict literal (a "
              "conditional-expression value counted as both arms) -- in the source "
              "order `maestro/dispatcher.py`'s `dispatch()` sets them. Regenerate with "
              "`make diagram` after touching `dispatch()`; `tests/test_diagram.py` fails "
              "`make test` otherwise.",
              "", f"{len(rows)} gates today.", "",
              "| # | outcome | source |", "|---|---------|--------|"]
    for i, (lineno, outcome) in enumerate(rows, start=1):
        lines.append(f"| {i} | `{outcome}` | `maestro/dispatcher.py:{lineno}` |")
    lines += ["", "## Sweep-level brakes", "",
              "These four short-circuit the entire spawn phase before any per-key "
              "outcome above reaches `spawned`/`would_spawn` -- a due key keeps "
              "whatever outcome the loop above already gave it, but nothing actually "
              "spawns this sweep.",
              "", "| brake | source | what it guards |", "|---|---|---|"]
    for name, lineno, desc in brakes:
        lines.append(f"| {name} | `maestro/dispatcher.py:{lineno}` | {desc} |")
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[str, str]:
    """Pure: {filename: content}. No I/O -- what both the writer and the
    drift-guard test call, so they can never diverge from each other."""
    return {
        "state-machine.md": render_state_diagram(),
        "dispatch-gates.md": render_dispatch_gates(),
    }


def write(docs_dir: Path | None = None) -> list[Path]:
    """Write both generated docs into `docs_dir` (default: the repo's own
    docs/). `docs_dir` is test-only -- `make diagram` always omits it, since
    the real committed artifacts live at `STATE_DIAGRAM_PATH`/
    `DISPATCH_GATES_PATH`, not wherever a test happens to point this."""
    target = docs_dir if docs_dir is not None else DOCS_DIR
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in generate().items():
        path = target / name
        path.write_text(content)
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", type=Path, default=None,
                         help="write into this directory instead of the repo's docs/ "
                              "(test isolation only)")
    args = parser.parse_args(argv)
    for path in write(args.docs_dir):
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
