"""Generate docs/state-machine.md and docs/dispatch-gates.md -- derived, never
retyped. Everything the two files describe is read straight off the running
source (``statemachine.TRANSITIONS``/``SLEEPING_PHASES``/``TERMINAL_PHASES``/
``ACTIVE_PHASES`` for the phase diagram; an AST walk of ``dispatcher.py`` for the
gate table), so the docs cannot drift from the code the way a hand-drawn diagram
would. Run via ``make diagram``; ``tests/test_diagram.py`` fails ``make test`` if
either committed file is stale.
"""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

from . import statemachine

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
STATE_DIAGRAM_PATH = DOCS_DIR / "state-machine.md"
DISPATCH_GATES_PATH = DOCS_DIR / "dispatch-gates.md"
DISPATCHER_SOURCE_PATH = REPO_ROOT / "maestro" / "dispatcher.py"

_HEADER = "<!-- GENERATED by `make diagram` (maestro/diagram.py) -- DO NOT EDIT. -->"


def _safe_id(phase_value: str) -> str:
    """Mermaid ``stateDiagram-v2`` state ids can't contain hyphens -- the
    parser tokenizes a bare hyphenated id as colliding with the ``-->``
    arrow (confirmed against the real mermaid parser: ``triaging -->
    awaiting-human`` fails with a 'Parse error ... Expecting SPACE, NL' on
    the second hyphen, and quoting the bare id in a transition doesn't fix
    it either). So every phase gets an underscore id here, aliased to its
    real, hyphenated name as a display label via `state "<name>" as <id>`."""
    return phase_value.replace("-", "_")


def render_state_diagram() -> str:
    """A mermaid ``stateDiagram-v2`` built solely from ``statemachine.py``'s
    ``TRANSITIONS``/``SLEEPING_PHASES``/``TERMINAL_PHASES``/``ACTIVE_PHASES``.
    Frozensets don't have a stable iteration order across interpreter runs
    (str hashing is salted per-process), so every set-derived line is sorted
    by phase value -- otherwise the drift-guard test would flap on hash seed
    alone, not on real drift."""
    lines = [_HEADER, "", "# maestro state machine", "",
              "Derived from `maestro/statemachine.py` (`TRANSITIONS`, `SLEEPING_PHASES`, "
              "`TERMINAL_PHASES`, `ACTIVE_PHASES`) -- regenerate with `make diagram` after "
              "touching that file; `tests/test_diagram.py` fails `make test` otherwise.",
              "", "```mermaid", "stateDiagram-v2"]
    for phase in statemachine.Phase:
        lines.append(f'    state "{phase.value}" as {_safe_id(phase.value)}')
    for phase in statemachine.Phase:
        for dst in sorted(statemachine.TRANSITIONS.get(phase, set()), key=lambda p: p.value):
            lines.append(f"    {_safe_id(phase.value)} --> {_safe_id(dst.value)}")
    lines += ["", "    classDef sleeping fill:#fff3cd,stroke:#997404",
              "    classDef terminal fill:#d1e7dd,stroke:#0f5132",
              "    classDef active fill:#cfe2ff,stroke:#084298"]
    for group, cls in ((statemachine.SLEEPING_PHASES, "sleeping"),
                        (statemachine.TERMINAL_PHASES, "terminal"),
                        (statemachine.ACTIVE_PHASES, "active")):
        names = " ".join(sorted(_safe_id(p.value) for p in group))
        if names:
            lines.append(f"    class {names} {cls}")
    lines += ["```", ""]
    return "\n".join(lines)


def _outcome_assignments(source: str) -> list[tuple[int, str]]:
    """(lineno, literal) for every ``decisions[<key>]["outcome"] = "<literal>"``
    assignment in `source`, sorted into source order. ``ast.walk`` visits nodes
    breadth-first, not in source order, so the sort is what actually orders
    these -- not incidental."""
    tree = ast.parse(source)
    found: list[tuple[int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not (isinstance(target, ast.Subscript)
                and isinstance(target.slice, ast.Constant)
                and target.slice.value == "outcome"
                and isinstance(target.value, ast.Subscript)
                and isinstance(target.value.value, ast.Name)
                and target.value.value.id == "decisions"):
            continue
        if not (isinstance(node.value, ast.Constant) and isinstance(node.value.value, str)):
            continue
        found.append((node.lineno, node.value.value))
    found.sort(key=lambda pair: pair[0])
    return found


def render_dispatch_gates() -> str:
    """The ordered dispatch gate table -- every ``decisions[key]["outcome"]``
    a sweep can assign, AST-walked out of ``dispatcher.py`` in source order.
    The only artifact that describes the resource layer (throttle, repo caps,
    credentials, runner preflight, spend ceiling, ...) statically."""
    rows = _outcome_assignments(DISPATCHER_SOURCE_PATH.read_text())
    lines = [_HEADER, "", "# dispatch gate table", "",
              "Every `decisions[key][\"outcome\"]` a sweep can assign, in the source "
              "order `maestro/dispatcher.py`'s `dispatch()` sets them. Regenerate with "
              "`make diagram` after touching `dispatch()`; `tests/test_diagram.py` fails "
              "`make test` otherwise.",
              "", f"{len(rows)} gates today.", "",
              "| # | outcome | source |", "|---|---------|--------|"]
    for i, (lineno, outcome) in enumerate(rows, start=1):
        lines.append(f"| {i} | `{outcome}` | `maestro/dispatcher.py:{lineno}` |")
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[str, str]:
    """Pure: {filename: content}. No I/O -- what both the writer and the
    drift-guard test call, so they can never diverge from each other."""
    return {
        "state-machine.md": render_state_diagram(),
        "dispatch-gates.md": render_dispatch_gates(),
    }


def write(docs_dir: Path | None = None) -> list[Path]:
    """Write both generated docs into `docs_dir` (default: the repo's own
    docs/). `docs_dir` is test-only -- `make diagram` always omits it, since
    the real committed artifacts live at `STATE_DIAGRAM_PATH`/
    `DISPATCH_GATES_PATH`, not wherever a test happens to point this."""
    target = docs_dir if docs_dir is not None else DOCS_DIR
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in generate().items():
        path = target / name
        path.write_text(content)
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", type=Path, default=None,
                         help="write into this directory instead of the repo's docs/ "
                              "(test isolation only)")
    args = parser.parse_args(argv)
    for path in write(args.docs_dir):
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
