"""Read-model projections — pure folds of all snapshots into human dashboards.

WORKSTATE.md and NEEDS-YOU.md are GENERATED and DO-NOT-EDIT. The human never edits
them, so regenerating them can never lose human input (the lost-update bug is gone
by construction). Written atomically; runs only as a dispatch phase, never per
reconciler (avoids a projection write race).
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Callable

from . import fleet, snapshot as snap_mod, store
from .dispatcher import list_keys, split_key
from .statemachine import Phase

# A row predicate: (home, snapshot) -> bool. Wider than a bare phase-set
# filter, so a caller can express a derived predicate too, not only phase
# membership.
RowPredicate = Callable[[Path, snap_mod.Snapshot], bool]

_BANNER = (
    "<!-- GENERATED by maestro — DO NOT EDIT.\n"
    "     To act: append to a ticket's inbox (`maestro ans <KEY> \"...\"`)\n"
    "     or edit its spec (`tickets/<KEY>/spec.md`). This file is a projection. -->\n"
)

# T-106: one exhaustive, hand-decided row per `Phase` -- the same RB-9 house
# pattern as `statemachine.PHASE_CLASS` and `dispatcher._PHASE_COMMAND_SUFFIX`
# -- top (needs a human first) to bottom (terminal noise). The five anchors
# from the ticket's spec, in their required relative order:
# awaiting-human > qa > implementing > ready > done. Everything else is
# slotted in the same spirit: DEGRADED (also needs-you) stays beside
# AWAITING_HUMAN; the sleeping/polling pipeline phases (IN_REVIEW,
# AWAITING_CI, VERIFYING) sit between QA and IMPLEMENTING in the order the
# PR lifecycle actually visits them; RESEARCHING/TRIAGING (still active, but
# nothing yet to review) sit between IMPLEMENTING and READY; TERMINATING
# (teardown) sits with DONE at the bottom. This is the TUI's own row order
# only -- `render()`'s separate WORKSTATE.md/NEEDS-YOU.md `order` list above
# is untouched (out of scope per the ticket's spec).
_TABLE_PHASE_ORDER = [
    Phase.AWAITING_HUMAN, Phase.DEGRADED, Phase.QA, Phase.IN_REVIEW,
    Phase.AWAITING_CI, Phase.VERIFYING, Phase.IMPLEMENTING, Phase.RESEARCHING,
    Phase.TRIAGING, Phase.READY, Phase.TERMINATING, Phase.DONE,
]
_missing_ranks = set(Phase) - set(_TABLE_PHASE_ORDER)
if _missing_ranks:
    raise AssertionError(
        f"Phase member(s) have no _TABLE_PHASE_ORDER rank: "
        f"{sorted(m.value for m in _missing_ranks)} -- add an explicit row "
        "before shipping (see statemachine.PHASE_CLASS for the pattern)."
    )
_PHASE_RANK: dict[str, int] = {p.value: i for i, p in enumerate(_TABLE_PHASE_ORDER)}


def _link(snap: snap_mod.Snapshot) -> str:
    if snap.pr_url and snap.pr_number:
        return f"[#{snap.pr_number}]({snap.pr_url})"
    return "—"


def _pr_cell(snap: snap_mod.Snapshot) -> str:
    if snap.pr_url and snap.pr_number:
        return f"[link={snap.pr_url}]#{snap.pr_number}[/link]"
    return "—"


def _sort_secondary(s: snap_mod.Snapshot):
    """Within the done group, newest-updated first; otherwise by key."""
    if s.phase == Phase.DONE.value:
        try:
            epoch = datetime.fromisoformat(s.updated_ts).timestamp()
        except (TypeError, ValueError):
            epoch = 0.0
        return -epoch
    return split_key(s.key)


def phase_predicate(phases: frozenset) -> RowPredicate:
    """Build a `RowPredicate` from a phase set -- the shape every filter used
    before predicates existed, kept as the on-ramp so old call sites
    (`ticket_rows(home, phases=...)`) don't need to hand-roll one."""
    values = {p.value for p in phases}
    return lambda home, s: s.phase in values


def load_snapshots(home: Path) -> list[snap_mod.Snapshot]:
    """Every ticket's snapshot, freshly loaded. The shared read behind
    `ticket_rows` and any caller needing a snapshot-level predicate rather
    than just the row tuples below."""
    return [snap_mod.load(home, k) for k in list_keys(home)]


def _row(home: Path, s: snap_mod.Snapshot) -> tuple[str, ...]:
    return (s.key, s.phase, snap_mod.display_title(home, s)[:64], _pr_cell(s),
            s.ci_state or "—", str(s.failure_count), s.key)


def rows_from_snapshots(home: Path, snaps) -> list[tuple[str, ...]]:
    """Sort *snaps* into table order and render each to a row tuple:
    (key, phase, title, pr, ci, fails, row_key), row_key == key (for
    DataTable keying)."""
    ordered = sorted(snaps, key=lambda s: (_PHASE_RANK.get(s.phase, 99), _sort_secondary(s)))
    return [_row(home, s) for s in ordered]


def ticket_rows(home: Path, phases: frozenset | None = None, *,
                 predicate: RowPredicate | None = None) -> list[tuple[str, ...]]:
    """Sorted rows for the live ticket table.

    If *predicate* is given it takes precedence; otherwise *phases* (a
    frozenset of `Phase`, back-compat with every existing caller) filters by
    phase membership. Neither given returns every ticket.
    """
    snaps = load_snapshots(home)
    if predicate is None and phases is not None:
        predicate = phase_predicate(phases)
    if predicate is not None:
        snaps = [s for s in snaps if predicate(home, s)]
    return rows_from_snapshots(home, snaps)


def render(home: Path) -> dict[str, str]:
    snaps = [snap_mod.load(home, k) for k in list_keys(home)]
    by_phase: dict[str, list[snap_mod.Snapshot]] = {}
    for s in snaps:
        by_phase.setdefault(s.phase, []).append(s)

    # ---- WORKSTATE.md -------------------------------------------------------
    lines = [_BANNER, f"# Workstate\n\n*Generated: {store.iso_now()}*\n"]
    # T-99 AC10: a missing/partial/uninitialized home can still fold phantom
    # rows below (RB-17's events/-with-no-tickets/ shape) -- stamp a banner
    # naming the gap instead of presenting them as authoritative.
    board = store.board_state(home)
    if board["state"] != "ok":
        lines.append(
            f"\n> ⚠️ **Board state: {board['state']}** — missing "
            f"{', '.join(board['missing_paths']) or '(nothing)'}. The rows below may be "
            "incomplete or phantom (`maestro status` / `maestro doctor` for detail; "
            "`maestro init` to repair).\n"
        )
    pause = fleet.pause_state(home, store.now_epoch())
    if pause is not None:
        reason = f" — {pause['reason']}" if pause.get("reason") else ""
        lines.append(f"\n> ⏸ **Fleet paused**{reason} (`maestro fleet resume` to lift)\n")
    order = [Phase.IMPLEMENTING, Phase.AWAITING_CI, Phase.IN_REVIEW, Phase.READY,
             Phase.TRIAGING, Phase.AWAITING_HUMAN, Phase.DEGRADED, Phase.TERMINATING]
    lines.append(f"\n**{len(snaps)} tickets** — "
                 + ", ".join(f"{p.value}:{len(by_phase.get(p.value, []))}"
                             for p in order if by_phase.get(p.value)) + "\n")
    lines.append("\n| Key | Phase | Title | PR | CI | Fails |")
    lines.append("|-----|-------|-------|----|----|-------|")
    for p in order:
        for s in sorted(by_phase.get(p.value, []), key=lambda x: split_key(x.key)):
            lines.append(
                f"| {s.key} | {s.phase} | {snap_mod.display_title(home, s)[:64]} | {_link(s)} "
                f"| {s.ci_state or '—'} | {s.failure_count} |"
            )
    workstate = "\n".join(lines) + "\n"

    # ---- NEEDS-YOU.md (the single human queue) ------------------------------
    nlines = [_BANNER, f"# Needs you\n\n*Generated: {store.iso_now()}*\n"]
    awaiting = by_phase.get(Phase.AWAITING_HUMAN.value, [])
    # RB-11: a burn-parked key (`should_park`'s dead-letter, tagged kind="burn")
    # is DEGRADED but is not "quietly waiting on a human" the way a generic
    # dead-letter or an open question is -- split it into its own section so a
    # human scanning this file can tell "parked, waiting for you" apart from
    # "burning" at a glance (spec AC5), instead of both reading identically
    # under one "Dead-lettered" heading.
    degraded_all = by_phase.get(Phase.DEGRADED.value, [])
    burning = [s for s in degraded_all if s.burning]
    degraded = [s for s in degraded_all if not s.burning]
    if not awaiting and not degraded and not burning:
        nlines.append("\nNothing is waiting on you. 🎉\n")
    if awaiting:
        nlines.append("\n## Questions\n")
        for s in sorted(awaiting, key=lambda x: split_key(x.key)):
            for qid, text in s.open_questions.items():
                nlines.append(f"- **{s.key}** — {text}")
                nlines.append(f"  - answer: `maestro ans {s.key} \"...\"`  (qid: {qid})")
    if burning:
        nlines.append("\n## Burning (parked -- no progress, repeated identical failures)\n")
        for s in sorted(burning, key=lambda x: split_key(x.key)):
            nlines.append(f"- **{s.key}** — {s.last_error or 'burning'} "
                          f"(failures: {s.failure_count})")
            nlines.append(f"  - revive: `maestro cmd {s.key} retry` · "
                          f"drop: `maestro cmd {s.key} discard`")
    if degraded:
        nlines.append("\n## Dead-lettered (need a decision)\n")
        for s in sorted(degraded, key=lambda x: split_key(x.key)):
            nlines.append(f"- **{s.key}** — {s.last_error or 'stalled'} "
                          f"(failures: {s.failure_count})")
            nlines.append(f"  - revive: `maestro cmd {s.key} retry` · "
                          f"drop: `maestro cmd {s.key} discard`")
    needs_you = "\n".join(nlines) + "\n"
    return {"WORKSTATE.md": workstate, "NEEDS-YOU.md": needs_you}


def write(home: Path) -> list[str]:
    out = render(home)
    derived = home / "derived"
    for name, text in out.items():
        store.atomic_write(derived / name, text)
    return list(out)
