"""Read-model projections — pure folds of all snapshots into human dashboards.

WORKSTATE.md and NEEDS-YOU.md are GENERATED and DO-NOT-EDIT. The human never edits
them, so regenerating them can never lose human input (the lost-update bug is gone
by construction). Written atomically; runs only as a dispatch phase, never per
reconciler (avoids a projection write race).
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Callable

from . import fleet, snapshot as snap_mod, store
from .dispatcher import list_keys, needs_approval, spec_tier, split_key
from .statemachine import Phase

# A row predicate: (home, snapshot) -> bool. Wider than the historic phase-set
# filter below -- needs-approval (GA-21) is a derived predicate, not a phase,
# so it can't be expressed as a `frozenset[Phase]`.
RowPredicate = Callable[[Path, snap_mod.Snapshot], bool]

_BANNER = (
    "<!-- GENERATED by maestro — DO NOT EDIT.\n"
    "     To act: append to a ticket's inbox (`maestro ans <KEY> \"...\"`)\n"
    "     or edit its spec (`tickets/<KEY>/spec.md`). This file is a projection. -->\n"
)

_TABLE_PHASE_ORDER = [
    Phase.IMPLEMENTING, Phase.AWAITING_CI, Phase.IN_REVIEW, Phase.READY,
    Phase.TRIAGING, Phase.AWAITING_HUMAN, Phase.DEGRADED, Phase.TERMINATING, Phase.DONE,
]
_PHASE_RANK: dict[str, int] = {p.value: i for i, p in enumerate(_TABLE_PHASE_ORDER)}


def _link(snap: snap_mod.Snapshot) -> str:
    if snap.pr_url and snap.pr_number:
        return f"[#{snap.pr_number}]({snap.pr_url})"
    return "—"


def _pr_cell(snap: snap_mod.Snapshot) -> str:
    if snap.pr_url and snap.pr_number:
        return f"[link={snap.pr_url}]#{snap.pr_number}[/link]"
    return "—"


def _sort_secondary(s: snap_mod.Snapshot):
    """Within the done group, newest-updated first; otherwise by key."""
    if s.phase == Phase.DONE.value:
        try:
            epoch = datetime.fromisoformat(s.updated_ts).timestamp()
        except (TypeError, ValueError):
            epoch = 0.0
        return -epoch
    return split_key(s.key)


def phase_predicate(phases: frozenset) -> RowPredicate:
    """Build a `RowPredicate` from a phase set -- the shape every filter used
    before predicates existed, kept as the on-ramp so old call sites
    (`ticket_rows(home, phases=...)`) don't need to hand-roll one."""
    values = {p.value for p in phases}
    return lambda home, s: s.phase in values


def load_snapshots(home: Path) -> list[snap_mod.Snapshot]:
    """Every ticket's snapshot, freshly loaded. The shared read behind
    `ticket_rows` and any caller needing a snapshot-level predicate (e.g. the
    TUI's needs-you filter, which needs `.approved` -- something the row
    tuples below don't carry)."""
    return [snap_mod.load(home, k) for k in list_keys(home)]


def _row(home: Path, s: snap_mod.Snapshot) -> tuple[str, ...]:
    return (s.key, s.phase, snap_mod.display_title(home, s)[:64], _pr_cell(s),
            s.ci_state or "—", str(spec_tier(home, s.key)), str(s.failure_count), s.key)


def rows_from_snapshots(home: Path, snaps) -> list[tuple[str, ...]]:
    """Sort *snaps* into table order and render each to a row tuple:
    (key, phase, title, pr, ci, tier, fails, row_key), row_key == key (for
    DataTable keying)."""
    ordered = sorted(snaps, key=lambda s: (_PHASE_RANK.get(s.phase, 99), _sort_secondary(s)))
    return [_row(home, s) for s in ordered]


def ticket_rows(home: Path, phases: frozenset | None = None, *,
                 predicate: RowPredicate | None = None) -> list[tuple[str, ...]]:
    """Sorted rows for the live ticket table.

    If *predicate* is given it takes precedence; otherwise *phases* (a
    frozenset of `Phase`, back-compat with every existing caller) filters by
    phase membership. Neither given returns every ticket.
    """
    snaps = load_snapshots(home)
    if predicate is None and phases is not None:
        predicate = phase_predicate(phases)
    if predicate is not None:
        snaps = [s for s in snaps if predicate(home, s)]
    return rows_from_snapshots(home, snaps)


def render(home: Path) -> dict[str, str]:
    snaps = [snap_mod.load(home, k) for k in list_keys(home)]
    by_phase: dict[str, list[snap_mod.Snapshot]] = {}
    for s in snaps:
        by_phase.setdefault(s.phase, []).append(s)

    # ---- WORKSTATE.md -------------------------------------------------------
    lines = [_BANNER, f"# Workstate\n\n*Generated: {store.iso_now()}*\n"]
    pause = fleet.pause_state(home, store.now_epoch())
    if pause is not None:
        reason = f" — {pause['reason']}" if pause.get("reason") else ""
        lines.append(f"\n> ⏸ **Fleet paused**{reason} (`maestro fleet resume` to lift)\n")
    order = [Phase.IMPLEMENTING, Phase.AWAITING_CI, Phase.IN_REVIEW, Phase.READY,
             Phase.TRIAGING, Phase.AWAITING_HUMAN, Phase.DEGRADED, Phase.TERMINATING]
    lines.append(f"\n**{len(snaps)} tickets** — "
                 + ", ".join(f"{p.value}:{len(by_phase.get(p.value, []))}"
                             for p in order if by_phase.get(p.value)) + "\n")
    lines.append("\n| Key | Phase | Title | PR | CI | Tier | Fails |")
    lines.append("|-----|-------|-------|----|----|------|-------|")
    for p in order:
        for s in sorted(by_phase.get(p.value, []), key=lambda x: split_key(x.key)):
            lines.append(
                f"| {s.key} | {s.phase} | {snap_mod.display_title(home, s)[:64]} | {_link(s)} "
                f"| {s.ci_state or '—'} | {spec_tier(home, s.key)} | {s.failure_count} |"
            )
    workstate = "\n".join(lines) + "\n"

    # ---- NEEDS-YOU.md (the single human queue) ------------------------------
    nlines = [_BANNER, f"# Needs you\n\n*Generated: {store.iso_now()}*\n"]
    awaiting = by_phase.get(Phase.AWAITING_HUMAN.value, [])
    # RB-11: a burn-parked key (`should_park`'s dead-letter, tagged kind="burn")
    # is DEGRADED but is not "quietly waiting on a human" the way a generic
    # dead-letter or an open question is -- split it into its own section so a
    # human scanning this file can tell "parked, waiting for you" apart from
    # "burning" at a glance (spec AC5), instead of both reading identically
    # under one "Dead-lettered" heading.
    degraded_all = by_phase.get(Phase.DEGRADED.value, [])
    burning = [s for s in degraded_all if s.burning]
    degraded = [s for s in degraded_all if not s.burning]
    # needs-approval is a derived predicate, not a phase (GA-21) -- it can park
    # a ticket that's still `implementing`, so it can't come from `by_phase`.
    gated = [s for s in snaps if needs_approval(home, s.key, s)]
    if not awaiting and not degraded and not burning and not gated:
        nlines.append("\nNothing is waiting on you. 🎉\n")
    if awaiting:
        nlines.append("\n## Questions\n")
        for s in sorted(awaiting, key=lambda x: split_key(x.key)):
            for qid, text in s.open_questions.items():
                nlines.append(f"- **{s.key}** — {text}")
                nlines.append(f"  - answer: `maestro ans {s.key} \"...\"`  (qid: {qid})")
    if burning:
        nlines.append("\n## Burning (parked -- no progress, repeated identical failures)\n")
        for s in sorted(burning, key=lambda x: split_key(x.key)):
            nlines.append(f"- **{s.key}** — {s.last_error or 'burning'} "
                          f"(failures: {s.failure_count})")
            nlines.append(f"  - revive: `maestro cmd {s.key} retry` · "
                          f"drop: `maestro cmd {s.key} discard`")
    if degraded:
        nlines.append("\n## Dead-lettered (need a decision)\n")
        for s in sorted(degraded, key=lambda x: split_key(x.key)):
            nlines.append(f"- **{s.key}** — {s.last_error or 'stalled'} "
                          f"(failures: {s.failure_count})")
            nlines.append(f"  - revive: `maestro cmd {s.key} retry` · "
                          f"drop: `maestro cmd {s.key} discard`")
    if gated:
        nlines.append("\n## Needs approval\n")
        for s in sorted(gated, key=lambda x: split_key(x.key)):
            nlines.append(f"- **{s.key}** — tier-{spec_tier(home, s.key)} change parked "
                          f"at the implementing gate")
            nlines.append(f"  - unblock: `maestro approve {s.key}`")
    needs_you = "\n".join(nlines) + "\n"
    return {"WORKSTATE.md": workstate, "NEEDS-YOU.md": needs_you}


def write(home: Path) -> list[str]:
    out = render(home)
    derived = home / "derived"
    for name, text in out.items():
        store.atomic_write(derived / name, text)
    return list(out)
