"""Read-model projections — pure folds of all snapshots into human dashboards.

WORKSTATE.md and NEEDS-YOU.md are GENERATED and DO-NOT-EDIT. The human never edits
them, so regenerating them can never lose human input (the lost-update bug is gone
by construction). Written atomically; runs only as a dispatch phase, never per
reconciler (avoids a projection write race).
"""
from __future__ import annotations

from pathlib import Path

from . import snapshot as snap_mod, store
from .dispatcher import list_keys
from .statemachine import Phase

_BANNER = (
    "<!-- GENERATED by maestro — DO NOT EDIT.\n"
    "     To act: append to a ticket's inbox (`maestro ans <KEY> \"...\"`)\n"
    "     or edit its spec (`tickets/<KEY>/spec.md`). This file is a projection. -->\n"
)

_TABLE_PHASE_ORDER = [
    Phase.IMPLEMENTING, Phase.AWAITING_CI, Phase.IN_REVIEW, Phase.READY,
    Phase.TRIAGING, Phase.AWAITING_HUMAN, Phase.DEGRADED, Phase.TERMINATING, Phase.DONE,
]
_PHASE_RANK: dict[str, int] = {p.value: i for i, p in enumerate(_TABLE_PHASE_ORDER)}


def _link(snap: snap_mod.Snapshot) -> str:
    if snap.pr_url and snap.pr_number:
        return f"[#{snap.pr_number}]({snap.pr_url})"
    return "—"


def _pr_cell(snap: snap_mod.Snapshot) -> str:
    if snap.pr_url and snap.pr_number:
        return f"#{snap.pr_number}"
    return "—"


def ticket_rows(home: Path) -> list[tuple[str, ...]]:
    """Sorted rows for the live ticket table.

    Each tuple: (key, phase, title, pr, ci, tier, fails, row_key)
    where row_key == key and is the last element for DataTable keying.
    """
    snaps = [snap_mod.load(home, k) for k in list_keys(home)]
    snaps.sort(key=lambda s: (_PHASE_RANK.get(s.phase, 99), s.key))
    return [
        (s.key, s.phase, (s.title or "")[:48], _pr_cell(s),
         s.ci_state or "—", s.tier or "—", str(s.failure_count), s.key)
        for s in snaps
    ]


def render(home: Path) -> dict[str, str]:
    snaps = [snap_mod.load(home, k) for k in list_keys(home)]
    by_phase: dict[str, list[snap_mod.Snapshot]] = {}
    for s in snaps:
        by_phase.setdefault(s.phase, []).append(s)

    # ---- WORKSTATE.md -------------------------------------------------------
    lines = [_BANNER, f"# Workstate\n\n*Generated: {store.iso_now()}*\n"]
    order = [Phase.IMPLEMENTING, Phase.AWAITING_CI, Phase.IN_REVIEW, Phase.READY,
             Phase.TRIAGING, Phase.AWAITING_HUMAN, Phase.DEGRADED, Phase.TERMINATING]
    lines.append(f"\n**{len(snaps)} tickets** — "
                 + ", ".join(f"{p.value}:{len(by_phase.get(p.value, []))}"
                             for p in order if by_phase.get(p.value)) + "\n")
    lines.append("\n| Key | Phase | Title | PR | CI | Tier | Fails |")
    lines.append("|-----|-------|-------|----|----|------|-------|")
    for p in order:
        for s in sorted(by_phase.get(p.value, []), key=lambda x: x.key):
            lines.append(
                f"| {s.key} | {s.phase} | {(s.title or '')[:48]} | {_link(s)} "
                f"| {s.ci_state or '—'} | {s.tier or '—'} | {s.failure_count} |"
            )
    workstate = "\n".join(lines) + "\n"

    # ---- NEEDS-YOU.md (the single human queue) ------------------------------
    nlines = [_BANNER, f"# Needs you\n\n*Generated: {store.iso_now()}*\n"]
    awaiting = by_phase.get(Phase.AWAITING_HUMAN.value, [])
    degraded = by_phase.get(Phase.DEGRADED.value, [])
    if not awaiting and not degraded:
        nlines.append("\nNothing is waiting on you. 🎉\n")
    if awaiting:
        nlines.append("\n## Questions\n")
        for s in sorted(awaiting, key=lambda x: x.key):
            for qid, text in s.open_questions.items():
                nlines.append(f"- **{s.key}** — {text}")
                nlines.append(f"  - answer: `maestro ans {s.key} \"...\"`  (qid: {qid})")
    if degraded:
        nlines.append("\n## Dead-lettered (need a decision)\n")
        for s in sorted(degraded, key=lambda x: x.key):
            nlines.append(f"- **{s.key}** — {s.last_error or 'stalled'} "
                          f"(failures: {s.failure_count})")
            nlines.append(f"  - revive: `maestro cmd {s.key} retry` · "
                          f"drop: `maestro cmd {s.key} discard`")
    needs_you = "\n".join(nlines) + "\n"
    return {"WORKSTATE.md": workstate, "NEEDS-YOU.md": needs_you}


def write(home: Path) -> list[str]:
    out = render(home)
    derived = home / "derived"
    for name, text in out.items():
        store.atomic_write(derived / name, text)
    return list(out)
