"""Context dossier fold (maestro/context.py) + the AcVerified self-review gate."""
import pytest

from maestro import cli, context, event_log, ops, snapshot as snap_mod, store
from maestro.statemachine import Phase

SPEC_TEMPLATE = """\
# {key}: {title}

approval_tier: 1
priority: 2
dependsOn: [{deps}]

## Intent
{intent}

## Acceptance criteria
{acs}
"""


def _write_spec(home, key, *, title="Test ticket", intent="do the thing",
                acs=("first thing", "second thing"), deps=()):
    ac_lines = "\n".join(f"- [ ] {t}" for t in acs)
    store.atomic_write(store.spec_path(home, key),
                       SPEC_TEMPLATE.format(key=key, title=title, deps=", ".join(deps),
                                            intent=intent, acs=ac_lines))


def _create(cfg, key, **spec_kwargs):
    _write_spec(cfg.home, key, **spec_kwargs)
    event_log.append(cfg.home, key, "TicketCreated",
                     {"title": spec_kwargs.get("title", "Test ticket"), "source": "test"}, actor="d")
    return snap_mod.rebuild(cfg.home, key)


def _evidence(what="ran pytest", where="tests/test_widget.py::test_builds", result="PASSED"):
    """A minimally-complete structured evidence dict for `verify_ac`."""
    return {"what": what, "where": where, "result": result}


# ---------------------------------------------------------------------------
# Dossier content: every section required by the ticket
# ---------------------------------------------------------------------------

def test_dossier_regenerated_by_ops_append_with_all_sections(cfg):
    home = cfg.home
    _create(cfg, "T-9", title="Dep ticket")
    ops.set_phase(cfg, "T-9", Phase.DONE, reason="done for the test")

    _create(cfg, "T-1", title="Widget", acs=("build the widget",), deps=("T-9",))

    ops.ask(cfg, "T-1", "Pick up T-1 — OK?", qid="q1")
    event_log.append(home, "T-1", "QuestionAnswered", {"qid": "q1", "answer": "ok"}, actor="human")
    ops.set_phase(cfg, "T-1", Phase.READY, reason="approved: ok")
    ops.set_phase(cfg, "T-1", Phase.IMPLEMENTING, reason="worktree ready")
    ops.fail(cfg, "T-1", "pytest red: test_widget failed")
    # CiObserved / ImplStepRecorded are appended raw (as the skill does via
    # `maestro append`), bypassing ops._append — the dossier still picks them
    # up on the next ops call because the fold reads the whole log fresh.
    event_log.append(home, "T-1", "CiObserved", {"state": "passing"}, actor="reconciler")
    event_log.append(home, "T-1", "ImplStepRecorded",
                     {"turn": 1, "role": "Implementer", "kind": "edit", "tool": "Edit",
                      "summary": "maestro/widget.py"}, actor="reconciler")
    ops.verify_ac(cfg, "T-1", 1, _evidence())
    ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green")

    path = context.context_path(home, "T-1")
    assert path.exists()
    text = path.read_text(encoding="utf-8")

    assert "GENERATED by maestro" in text
    assert "# Context: T-1 — Widget" in text
    # Phase history: verbatim reasons
    assert "approved: ok" in text
    assert "worktree ready" in text
    assert "tests green" in text
    # Answered questions: verbatim Q + A
    assert "Pick up T-1 — OK?" in text
    assert "ok" in text
    # Failures
    assert "pytest red: test_widget failed" in text
    # CI observations
    assert "passing" in text
    # Impl steps
    assert "maestro/widget.py" in text
    # Dependencies + their phase
    assert "T-9: done" in text


def test_dossier_reflects_missing_dependency_gracefully(cfg):
    """A dependsOn key with no ticket yet still renders (default snapshot phase)."""
    _create(cfg, "T-1", deps=("T-404",))
    ops.observe_spec(cfg, "T-1")

    text = context.context_path(cfg.home, "T-1").read_text(encoding="utf-8")
    assert "T-404: triaging" in text


# ---------------------------------------------------------------------------
# Determinism: same log folds to byte-identical output
# ---------------------------------------------------------------------------

def test_render_is_byte_identical_for_the_same_events(cfg):
    _create(cfg, "T-1", acs=("do the thing",))
    ops.ask(cfg, "T-1", "OK?", qid="q1")
    event_log.append(cfg.home, "T-1", "QuestionAnswered", {"qid": "q1", "answer": "yes"}, actor="human")
    ops.set_phase(cfg, "T-1", Phase.READY, reason="approved: yes")

    events = event_log.read(cfg.home, "T-1")
    first = context.render("T-1", "Test ticket", events, {"T-9": "done"})
    second = context.render("T-1", "Test ticket", events, {"T-9": "done"})

    assert first == second


def test_render_output_is_stable_across_regenerate_calls(cfg):
    _create(cfg, "T-1")
    ops.set_phase(cfg, "T-1", Phase.READY, reason="approved: ok")

    path = context.context_path(cfg.home, "T-1")
    first = path.read_text(encoding="utf-8")
    context.regenerate(cfg.home, "T-1")  # no new events since
    second = path.read_text(encoding="utf-8")

    assert first == second


# ---------------------------------------------------------------------------
# Token-bounded per-section caps
# ---------------------------------------------------------------------------

def test_dossier_caps_phase_history_and_notes_the_omission(cfg):
    _create(cfg, "T-1", acs=())  # no ACs -- unrelated to the AC gate, ping-pongs freely
    # Ping-pong past the cap so there are more phase changes than MAX_PHASE_CHANGES.
    total = context.MAX_PHASE_CHANGES + 5
    for i in range(total):
        dst = Phase.IMPLEMENTING if i % 2 == 0 else Phase.AWAITING_CI
        ops.set_phase(cfg, "T-1", dst, reason=f"iteration {i}")

    text = context.context_path(cfg.home, "T-1").read_text(encoding="utf-8")
    assert "earlier phase change(s) omitted" in text
    assert "iteration 0" not in text  # oldest dropped
    assert f"iteration {total - 1}" in text  # newest kept


# ---------------------------------------------------------------------------
# AcVerified event + verify-ac verb
# ---------------------------------------------------------------------------

def test_verify_ac_appends_event_and_reduces_unverified_count(cfg):
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget", "document it"))
    snap = snap_mod.load(home, "T-1")
    spec_text = store.spec_path(home, "T-1").read_text(encoding="utf-8")
    assert snap.acs_unverified(spec_text) == 2

    ev1 = _evidence(where="tests/test_widget.py::test_builds", result="PASSED")
    h = ops.verify_ac(cfg, "T-1", 1, ev1)
    snap = snap_mod.load(home, "T-1")
    assert snap.ac_verified[h] == ev1
    assert snap.acs_unverified(spec_text) == 1

    ev2 = _evidence(what="read the diff", where="README.md", result="widget docs present")
    ops.verify_ac(cfg, "T-1", 2, ev2)
    snap = snap_mod.load(home, "T-1")
    assert snap.acs_unverified(spec_text) == 0


def test_verify_ac_via_real_cli(cfg):
    """CLI-driven, per the QA convention: exercise the actual `maestro` surface."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))

    rc = cli.main(["--home", str(home), "verify-ac", "T-1", "--ac", "1",
                   "--what", "ran pytest", "--where", "tests/test_widget.py::test_builds",
                   "--result", "PASSED"])
    assert rc == 0

    events = event_log.read(home, "T-1")
    ac_events = [e for e in events if e["type"] == "AcVerified"]
    assert len(ac_events) == 1
    assert ac_events[0]["payload"]["evidence"] == {
        "what": "ran pytest", "where": "tests/test_widget.py::test_builds", "result": "PASSED"}
    assert ac_events[0]["payload"]["ac_index"] == 1


def test_verify_ac_is_idempotent_by_step_id(cfg):
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, _evidence(result="first evidence"))
    ops.verify_ac(cfg, "T-1", 1, _evidence(result="second evidence — should be a no-op"))

    events = event_log.read(cfg.home, "T-1")
    ac_events = [e for e in events if e["type"] == "AcVerified"]
    assert len(ac_events) == 1
    assert ac_events[0]["payload"]["evidence"]["result"] == "first evidence"


def test_verify_ac_out_of_range_raises(cfg):
    _create(cfg, "T-1", acs=("only one thing",))
    with pytest.raises(store.MaestroError, match="out of range"):
        ops.verify_ac(cfg, "T-1", 2, _evidence())


def test_verify_ac_rejects_evidence_missing_a_required_field(cfg):
    """AC1: a call missing any of the three structured-evidence fields is rejected
    before anything is appended — 'done' is no longer an acceptable attestation."""
    _create(cfg, "T-1", acs=("build the widget",))

    for incomplete in (
        {"what": "ran pytest", "where": "tests/test_widget.py"},          # no result
        {"what": "ran pytest", "result": "PASSED"},                       # no where
        {"where": "tests/test_widget.py", "result": "PASSED"},            # no what
        {"what": "ran pytest", "where": "tests/test_widget.py", "result": "   "},  # blank
    ):
        with pytest.raises(store.MaestroError, match="missing required field"):
            ops.verify_ac(cfg, "T-1", 1, incomplete)

    assert event_log.read(cfg.home, "T-1")[-1]["type"] != "AcVerified"


def test_verify_ac_rejects_incomplete_evidence_via_real_cli(cfg):
    """The CLI surface refuses too (argparse `required=True` on --what/--where/--result)."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))

    with pytest.raises(SystemExit) as exc:
        cli.main(["--home", str(home), "verify-ac", "T-1", "--ac", "1",
                  "--what", "ran pytest", "--where", "tests/test_widget.py"])  # no --result
    assert exc.value.code != 0
    assert not [e for e in event_log.read(home, "T-1") if e["type"] == "AcVerified"]


def test_spec_edit_desyncs_stale_attestation(cfg):
    """A human edit to an AC's line invalidates its old attestation by content
    hash — proving desync detection instead of a stale/mismatched index match."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, _evidence(result="verified against the original wording"))

    spec_text = store.spec_path(home, "T-1").read_text(encoding="utf-8")
    snap = snap_mod.load(home, "T-1")
    assert snap.acs_unverified(spec_text) == 0

    # Human edits the AC's wording (still AC #1, but different content hash).
    _write_spec(home, "T-1", acs=("build the widget with a handle",))
    new_spec_text = store.spec_path(home, "T-1").read_text(encoding="utf-8")

    snap = snap_mod.load(home, "T-1")  # unchanged event log
    assert snap.acs_unverified(new_spec_text) == 1  # the stale attestation no longer counts


# ---------------------------------------------------------------------------
# The AC gate at set-phase awaiting-ci: refusal, and the --force escape hatch
# ---------------------------------------------------------------------------

def test_set_phase_awaiting_ci_refuses_when_acs_unverified(cfg):
    """AC2: unattested ACs make the transition exit non-zero and append NO
    PhaseChanged event — no longer a soft Note, an enforced gate."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget", "document it"))
    seq_before = snap_mod.load(home, "T-1").observed_seq

    with pytest.raises(store.MaestroError, match="2 acceptance criteria unverified"):
        ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green")

    assert snap_mod.load(home, "T-1").phase != Phase.AWAITING_CI.value
    evs = event_log.read(home, "T-1", since=seq_before)
    assert [e for e in evs if e["type"] == "PhaseChanged"] == []


def test_set_phase_awaiting_ci_refuses_via_real_cli_with_nonzero_exit(cfg):
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))

    rc = cli.main(["--home", str(home), "set-phase", "T-1", "awaiting-ci", "--reason", "tests green"])
    assert rc != 0

    assert snap_mod.load(home, "T-1").phase != Phase.AWAITING_CI.value
    assert not [e for e in event_log.read(home, "T-1") if e["type"] == "PhaseChanged"]


def test_set_phase_awaiting_ci_succeeds_once_all_acs_verified(cfg):
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, _evidence())

    ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green")

    assert snap_mod.load(home, "T-1").phase == Phase.AWAITING_CI.value
    events = event_log.read(home, "T-1")
    notes = [e for e in events if e["type"] == "Note" and "unverified" in e["payload"].get("text", "")]
    assert notes == []


def test_set_phase_force_overrides_gate_and_records_actor(cfg):
    """AC3: --force lets a human push a ticket through with unattested ACs, and
    the event log records who did it."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget", "document it"))

    ev = ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="human override",
                       actor="valentin", force=True)

    assert ev is not None
    assert ev["payload"]["forced_by"] == "valentin"
    snap = snap_mod.load(home, "T-1")
    assert snap.phase == Phase.AWAITING_CI.value

    events = event_log.read(home, "T-1")
    changed = [e for e in events if e["type"] == "PhaseChanged" and e["payload"].get("phase") == "awaiting-ci"]
    assert changed and changed[-1]["payload"]["forced_by"] == "valentin"
    forced_notes = [e for e in events if e["type"] == "Note" and "forced past" in e["payload"].get("text", "")]
    assert len(forced_notes) == 1
    assert "valentin" in forced_notes[0]["payload"]["text"]
    assert "2 unverified" in forced_notes[0]["payload"]["text"]


def test_set_phase_force_not_needed_and_inert_when_all_acs_verified(cfg):
    """--force is a no-op marker when there was nothing to override."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, _evidence())

    ev = ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green", force=True)

    assert "forced_by" not in ev["payload"]
    events = event_log.read(home, "T-1")
    assert not [e for e in events if e["type"] == "Note" and "forced past" in e["payload"].get("text", "")]


def test_set_phase_force_via_real_cli(cfg):
    """AC4: a real-CLI test proving both the refusal and the forced path, over a
    temp home, driving the actual `maestro` verbs."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))

    # Refusal first: no --force, unattested AC -> non-zero exit, no event.
    rc = cli.main(["--home", str(home), "set-phase", "T-1", "awaiting-ci", "--reason", "tests green"])
    assert rc != 0
    assert not [e for e in event_log.read(home, "T-1") if e["type"] == "PhaseChanged"]

    # The forced path: --force pushes it through and records the actor.
    rc = cli.main(["--home", str(home), "set-phase", "T-1", "awaiting-ci",
                   "--reason", "human override", "--actor", "valentin", "--force"])
    assert rc == 0

    snap = snap_mod.load(home, "T-1")
    assert snap.phase == Phase.AWAITING_CI.value
    events = event_log.read(home, "T-1")
    changed = [e for e in events if e["type"] == "PhaseChanged" and e["payload"].get("phase") == "awaiting-ci"]
    assert changed and changed[-1]["payload"]["forced_by"] == "valentin"
