"""T-64/OC-6: the opencode declarative config write path -- both pieces
``sessions.py:341-347`` left waiting (``--agent <name>``'s file,
``runner_permissions.opencode_bash_permissions``'s only real caller) plus the
local ``ollama`` provider block ``OpencodeCliSessions`` needs to resolve its
model. All three are generated by ``maestro install-commands`` (both
``--repo`` and ``--user``, GA-15's existing verb) into ``opencode.jsonc`` +
``.opencode/agent/*.md``, one source, idempotent, never a blanket allow.

The ``external_directory`` fix (a reconcile skill's Read tool call for
``<MAESTRO_HOME>/tickets/<KEY>/spec.md`` -- outside opencode's own ``--dir``
worktree -- was denied: "The user rejected permission...") was verified for
real against a live ``opencode run`` + a real ``qwen3-coder:30b`` tool call
during this ticket's implementation (not reproduced here as an automated test
-- no ollama daemon/opencode binary is assumed present in CI, matching how
``test_e2e_opencode.py``/``test_runner_opencode_config.py`` already stub the
opencode executable rather than depend on a real one). What IS reproduced here
is the exact glob shape that live run confirmed opencode requests
(``<dir>/*``) via Python's own ``fnmatch`` -- a real matcher, not a hand-rolled
mock -- as a portable regression guard.
"""
from __future__ import annotations

import fnmatch
import io
import json
import sys

from maestro import dispatcher as disp, runner_permissions, skills_install
from maestro.cli import main as cli_main
from maestro.config import Config
from maestro.sessions import OPENCODE_MODEL_PROVIDER
from maestro.statemachine import Phase

from test_runner_preflight import _seed


def _write_config(home, text: str) -> None:
    (home / "config.toml").write_text(text)


def _doctor(home):
    buf = io.StringIO()
    old = sys.stdout
    sys.stdout = buf
    try:
        code = cli_main(["--home", str(home), "doctor"])
    finally:
        sys.stdout = old
    return code, json.loads(buf.getvalue())


# ---------------------------------------------------------------------------
# AC2/AC3: opencode_permission_block -- the real caller, admits the read +
# maestro verbs, never a blanket allow.
# ---------------------------------------------------------------------------

def test_permission_block_allows_maestro_verbs_derived_from_one_definition(home):
    perms = runner_permissions.opencode_permission_block(home)
    assert perms["bash"]["maestro snapshot *"] == "allow"
    assert perms["bash"]["maestro env"] == "allow"
    # sourced from dispatcher.AGENT_TOOL_VERBS -- never a second hand-typed list
    for verb in disp.AGENT_TOOL_VERBS:
        assert perms["bash"][f"maestro {verb} *"] == "allow"
    # the destructive-command guard's own deny/ask entries are still present --
    # a real caller of opencode_bash_permissions, not a replacement for it
    assert any(action == "deny" for action in perms["bash"].values())


def test_permission_block_never_admits_a_blanket_allow(home):
    perms = runner_permissions.opencode_permission_block(home)
    assert perms["bash"].get("*") != "allow"
    assert "*" not in perms["external_directory"]
    for pattern in perms["external_directory"]:
        assert pattern != "*"
        assert str(home.resolve()) in pattern  # scoped under MAESTRO_HOME, never home-agnostic


def test_permission_block_external_directory_admits_a_real_spec_read(home):
    """Reproduces the exact glob shape a live opencode run requested for a Read
    tool call outside its own --dir (verified manually for this ticket, spec
    Notes) -- ``<containing-dir>/*`` -- against a real fnmatch matcher."""
    perms = runner_permissions.opencode_permission_block(home)
    spec_dir = (home / "tickets" / "T-64").resolve()
    requested_pattern = f"{spec_dir}/*"
    assert any(fnmatch.fnmatch(requested_pattern, allowed)
               for allowed, action in perms["external_directory"].items() if action == "allow")
    # inbox and derived (snapshots/context) are covered the same way
    for sub in ("inbox", "derived"):
        requested = f"{(home / sub).resolve()}/*"
        assert any(fnmatch.fnmatch(requested, allowed)
                   for allowed, action in perms["external_directory"].items() if action == "allow")


def test_permission_block_external_directory_does_not_admit_an_unrelated_path(home):
    perms = runner_permissions.opencode_permission_block(home)
    outside = "/etc/passwd"
    assert not any(fnmatch.fnmatch(outside, p) for p in perms["external_directory"])


def test_permission_block_honors_a_phase_narrowed_verb_set(home):
    """RB-16 fix round: `verbs=` narrows the ALLOW set (unaffected: the
    destructive-guard denies), and a verb outside it is simply absent, not
    "allow" or "deny" -- opencode's own default (`ask`) then applies, same as
    any other unmatched bash pattern."""
    narrow = runner_permissions.opencode_permission_block(home, verbs=("snapshot", "env"))
    assert narrow["bash"]["maestro snapshot *"] == "allow"
    assert "maestro finalize *" not in narrow["bash"]
    full = runner_permissions.opencode_permission_block(home)
    assert full["bash"]["maestro finalize *"] == "allow"  # default (verbs=None) is still the ceiling


# ---------------------------------------------------------------------------
# AC1/AC4: install-commands writes opencode.jsonc + per-phase --agent stubs,
# idempotently, from both --repo and --user.
# ---------------------------------------------------------------------------

def test_install_repo_writes_opencode_config_and_agent_stubs(home, tmp_path):
    repo = tmp_path / "acme"
    _write_config(home, f'[repos.acme]\npath = "{repo}"\n'
                        '[maestro]\nrunner_enabled = ["claude", "opencode"]\n')

    assert cli_main(["--home", str(home), "install-commands", "--repo", "acme"]) == 0

    config_path = repo / ".opencode" / "opencode.jsonc"
    assert config_path.exists()
    written = json.loads(config_path.read_text())
    assert written["permission"] == runner_permissions.opencode_permission_block(home)
    assert written["$schema"] == "https://opencode.ai/config.json"

    agent_dir = repo / ".opencode" / "agent"
    installed = sorted(p.name for p in agent_dir.iterdir())
    assert installed == sorted(skills_install.PAYLOAD_NAMES)
    one = (agent_dir / "maestro-reconcile-implementing.md").read_text()
    assert "mode: primary" in one
    assert "description:" in one


def test_agent_stub_permission_bash_is_phase_narrowed_not_the_flat_ceiling(home, tmp_path):
    """RB-16 fix round -- the exact gap QA's own evidence named: a qa-phase
    ticket with runner=opencode could still call `maestro finalize` because
    every phase's opencode surface carried the flat AGENT_TOOL_VERBS ceiling.
    Each phase's own --agent stub now embeds a permission.bash override
    scoped to exactly the verbs `dispatcher.phase_verb_grant` (the claude
    runner's own source) grants that phase -- verified against a real
    installed opencode (`opencode debug config`) during this ticket, see
    `runner_permissions.opencode_permission_block`'s docstring."""
    repo = tmp_path / "acme"
    _write_config(home, f'[repos.acme]\npath = "{repo}"\n'
                        '[maestro]\nrunner_enabled = ["claude", "opencode"]\n')
    assert cli_main(["--home", str(home), "install-commands", "--repo", "acme"]) == 0

    agent_dir = repo / ".opencode" / "agent"
    qa_stub = (agent_dir / "maestro-reconcile-qa.md").read_text()
    assert '"maestro finalize *": allow' not in qa_stub
    assert '"maestro snapshot *": allow' in qa_stub

    impl_stub = (agent_dir / "maestro-reconcile-implementing.md").read_text()
    assert '"maestro finalize *": allow' in impl_stub

    triaging_stub = (agent_dir / "maestro-reconcile-triaging.md").read_text()
    assert '"maestro verify-ac *": allow' not in triaging_stub
    assert '"maestro ask *": allow' in triaging_stub


def test_install_repo_opencode_config_and_agents_idempotent(home, tmp_path):
    repo = tmp_path / "acme"
    _write_config(home, f'[repos.acme]\npath = "{repo}"\n'
                        '[maestro]\nrunner_enabled = ["claude", "opencode"]\n')

    assert cli_main(["--home", str(home), "install-commands", "--repo", "acme"]) == 0
    config_path = repo / ".opencode" / "opencode.jsonc"
    agent_dir = repo / ".opencode" / "agent"
    before_cfg = (config_path.read_text(), config_path.stat().st_mtime)
    before_agents = {p.name: (p.read_text(), p.stat().st_mtime) for p in agent_dir.iterdir()}

    assert cli_main(["--home", str(home), "install-commands", "--repo", "acme"]) == 0
    after_cfg = (config_path.read_text(), config_path.stat().st_mtime)
    after_agents = {p.name: (p.read_text(), p.stat().st_mtime) for p in agent_dir.iterdir()}
    assert before_cfg == after_cfg
    assert before_agents == after_agents
    assert [p for p in agent_dir.iterdir() if p.is_dir()] == []


def test_install_user_writes_opencode_config_and_agent_stubs(home, tmp_path, monkeypatch):
    user_dir = tmp_path / "user-commands"
    opencode_user_dir = tmp_path / "opencode-user-commands"
    monkeypatch.setenv("MAESTRO_USER_COMMANDS_DIR", str(user_dir))
    monkeypatch.setenv("MAESTRO_OPENCODE_COMMANDS_DIR", str(opencode_user_dir))
    _write_config(home, '[maestro]\nrunner_enabled = ["claude", "opencode"]\n')

    assert cli_main(["--home", str(home), "install-commands", "--user"]) == 0

    config_path = opencode_user_dir.parent / "opencode.jsonc"
    assert config_path.exists()
    written = json.loads(config_path.read_text())
    assert written["permission"] == runner_permissions.opencode_permission_block(home)

    agent_dir = opencode_user_dir.parent / "agent"
    assert sorted(p.name for p in agent_dir.iterdir()) == sorted(skills_install.PAYLOAD_NAMES)


# ---------------------------------------------------------------------------
# T-91: the opencode payload is gated on "opencode" in cfg.runner_enabled --
# the skip is reported explicitly in the verb's JSON output, and doctor stays
# green either way (a gated claude-only board never needed the opencode
# config to begin with).
# ---------------------------------------------------------------------------

def test_gated_install_names_the_skip_reason_in_json_output(home, tmp_path, capsys):
    """AC4: parsed from real stdout, not the returned dict alone -- the
    default claude-only board (no `runner_enabled` line) skips the opencode
    payload and says why, mentioning `runner_enabled` by name."""
    repo = tmp_path / "acme"
    _write_config(home, f'[repos.acme]\npath = "{repo}"\n')

    assert cli_main(["--home", str(home), "install-commands", "--repo", "acme"]) == 0
    out = json.loads(capsys.readouterr().out)
    assert out["opencode_skipped"]
    assert "runner_enabled" in out["opencode_skipped"]
    assert out["opencode_written"] == []
    assert out["opencode_agent_written"] == []
    assert out["opencode_config_written"] is False


def test_ungated_install_reports_no_skip_in_json_output(home, tmp_path, capsys):
    """The counterpart -- with opencode admitted, nothing is skipped."""
    repo = tmp_path / "acme"
    _write_config(home, f'[repos.acme]\npath = "{repo}"\n'
                        '[maestro]\nrunner_enabled = ["claude", "opencode"]\n')

    assert cli_main(["--home", str(home), "install-commands", "--repo", "acme"]) == 0
    out = json.loads(capsys.readouterr().out)
    assert out["opencode_skipped"] is None


def test_doctor_reconciler_permissions_ok_on_claude_only_board_after_gated_install(
        home, tmp_path, monkeypatch):
    """AC7 (first direction): `reconciler_permissions` reaches `ok` for a
    claude-runner ticket on a claude-only board exactly as it always did --
    the gated (skipped) opencode install alongside it changes nothing about
    that path (the check inspects Claude Code's own settings.json grants,
    which `install-commands`'s Claude side is unaffected by this ticket's
    gate)."""
    monkeypatch.setenv("MAESTRO_USER_SETTINGS_PATH", str(tmp_path / "no-user-settings.json"))
    repo = home / "repo"
    repo.mkdir()
    (repo / ".claude").mkdir()
    (repo / ".claude" / "settings.json").write_text(json.dumps(
        {"permissions": {"allow": disp.maestro_verb_grant() +
                          ["Bash(git:*)", "Bash(gh:*)", "Bash(python3:*)"]}}))
    _write_config(home, f'[maestro]\nrepo_path = "{repo}"\nmin_spawn_interval = 0\n')
    _seed(home, "T-1", phase=Phase.IMPLEMENTING, runner=None)

    out = cli_main(["--home", str(home), "install-commands", "--repo", "default"])
    assert out == 0
    assert not (repo / ".opencode").exists()  # the gate held -- claude-only board

    code, report = _doctor(home)
    assert code == 0
    check = next(c for c in report["checks"] if c["name"] == "reconciler_permissions")
    assert check["status"] == "ok"
    assert check["missing_by_repo"] == {}


# ---------------------------------------------------------------------------
# AC7: provider block generated from [runner.opencode], ollama/ composed once
# ---------------------------------------------------------------------------

def test_provider_block_registers_configured_models(home):
    cfg = Config(home=home, provider_config={"runner": {"opencode": {"models": ["qwen3-coder:30b"]}}})
    block = skills_install._opencode_provider_block(cfg)
    assert block[OPENCODE_MODEL_PROVIDER]["models"] == {"qwen3-coder:30b": {"tool_call": True}}
    assert block[OPENCODE_MODEL_PROVIDER]["options"]["baseURL"].endswith("/v1")


def test_provider_block_falls_back_to_board_wide_runner_model(home):
    cfg = Config(home=home, runner_model="qwen3-coder:30b")
    block = skills_install._opencode_provider_block(cfg)
    assert "qwen3-coder:30b" in block[OPENCODE_MODEL_PROVIDER]["models"]


def test_provider_block_empty_when_nothing_configured(home):
    cfg = Config(home=home)
    assert skills_install._opencode_provider_block(cfg) == {}
    assert "provider" not in skills_install._opencode_declarative_config(cfg)


def test_provider_block_host_override_feeds_base_url(home):
    cfg = Config(home=home, provider_config={
        "runner": {"opencode": {"models": ["a:1b"], "host": "example.internal:11434"}}})
    block = skills_install._opencode_provider_block(cfg)
    assert block[OPENCODE_MODEL_PROVIDER]["options"]["baseURL"] == "http://example.internal:11434/v1"


def test_config_load_rejects_unrecognized_and_accepts_new_opencode_keys(home):
    from maestro import config as config_mod, store as store_mod
    (home / "config.toml").write_text('[runner.opencode]\nmodels = ["a:1b"]\nhost = "x:1"\n')
    cfg = config_mod.load(str(home))
    assert cfg.provider_config["runner"]["opencode"]["models"] == ["a:1b"]

    (home / "config.toml").write_text('[runner.opencode]\nmodel = ["typo"]\n')
    try:
        config_mod.load(str(home))
        raise AssertionError("expected a MaestroError for the unrecognized key")
    except store_mod.MaestroError as e:
        assert "model" in str(e)


# ---------------------------------------------------------------------------
# AC5: health.check_reconciler_permissions -- warn then ok for opencode
# ---------------------------------------------------------------------------

def test_doctor_warns_missing_opencode_permission_config_then_ok_once_installed(home):
    _write_config(home, f'[maestro]\nrepo_path = "{home / "repo"}"\nrunner = "opencode"\n'
                        'runner_enabled = ["claude", "opencode"]\nmin_spawn_interval = 0\n')
    (home / "repo").mkdir()
    _seed(home, "T-1", phase=Phase.IMPLEMENTING, runner="opencode", runner_model="a:1b")

    code, report = _doctor(home)
    assert code == 0
    check = next(c for c in report["checks"] if c["name"] == "reconciler_permissions")
    assert check["status"] == "warn"
    assert "default" in check["missing_by_repo"]
    assert check["not_applicable_by_repo"] == {}

    assert cli_main(["--home", str(home), "install-commands", "--repo", "default"]) == 0

    code, report = _doctor(home)
    assert code == 0
    check = next(c for c in report["checks"] if c["name"] == "reconciler_permissions")
    assert check["status"] == "ok"
    assert check["missing_by_repo"] == {}


def test_doctor_warns_when_installed_config_is_stale(home):
    """A config.toml edit since the last install-commands run (e.g. a new
    [runner.opencode] table) must re-warn, not read a byte-stale file as ok --
    QW-1's rule: 'close but not exactly what would be generated now' warns."""
    repo = home / "repo"
    repo.mkdir()
    _write_config(home, f'[maestro]\nrepo_path = "{repo}"\nrunner = "opencode"\n'
                        'runner_enabled = ["claude", "opencode"]\nmin_spawn_interval = 0\n')
    _seed(home, "T-1", phase=Phase.IMPLEMENTING, runner="opencode", runner_model="a:1b")
    assert cli_main(["--home", str(home), "install-commands", "--repo", "default"]) == 0

    # Simulate drift: hand-edit the installed file after the fact.
    config_path = repo / ".opencode" / "opencode.jsonc"
    stale = json.loads(config_path.read_text())
    stale["permission"]["bash"]["maestro snapshot *"] = "ask"
    config_path.write_text(json.dumps(stale, indent=2) + "\n")

    code, report = _doctor(home)
    assert code == 0
    check = next(c for c in report["checks"] if c["name"] == "reconciler_permissions")
    assert check["status"] == "warn"


# ---------------------------------------------------------------------------
# read_opencode_config -- never raises, None on missing/malformed
# ---------------------------------------------------------------------------

def test_read_opencode_config_none_when_missing(tmp_path):
    assert skills_install.read_opencode_config(tmp_path / "nope.jsonc") is None


def test_read_opencode_config_none_when_malformed(tmp_path):
    p = tmp_path / "bad.jsonc"
    p.write_text("{not json")
    assert skills_install.read_opencode_config(p) is None


def test_read_opencode_config_round_trips_generator_output(home):
    cfg = Config(home=home, runner_model="a:1b")
    p = home / "opencode.jsonc"
    p.write_text(skills_install._dump_opencode_config(cfg))
    assert skills_install.read_opencode_config(p) == skills_install._opencode_declarative_config(cfg)
