"""Context dossier fold (maestro/context.py) + the AcVerified self-review gate."""
import pytest

from maestro import cli, context, event_log, ops, snapshot as snap_mod, store
from maestro.statemachine import Phase

SPEC_TEMPLATE = """\
# {key}: {title}

approval_tier: 1
priority: 2
dependsOn: [{deps}]

## Intent
{intent}

## Acceptance criteria
{acs}
"""


def _write_spec(home, key, *, title="Test ticket", intent="do the thing",
                acs=("first thing", "second thing"), deps=()):
    ac_lines = "\n".join(f"- [ ] {t}" for t in acs)
    store.atomic_write(store.spec_path(home, key),
                       SPEC_TEMPLATE.format(key=key, title=title, deps=", ".join(deps),
                                            intent=intent, acs=ac_lines))


def _create(cfg, key, **spec_kwargs):
    _write_spec(cfg.home, key, **spec_kwargs)
    event_log.append(cfg.home, key, "TicketCreated",
                     {"title": spec_kwargs.get("title", "Test ticket"), "source": "test"}, actor="d")
    return snap_mod.rebuild(cfg.home, key)


# ---------------------------------------------------------------------------
# Dossier content: every section required by the ticket
# ---------------------------------------------------------------------------

def test_dossier_regenerated_by_ops_append_with_all_sections(cfg):
    home = cfg.home
    _create(cfg, "T-9", title="Dep ticket")
    ops.set_phase(cfg, "T-9", Phase.DONE, reason="done for the test")

    _create(cfg, "T-1", title="Widget", acs=("build the widget",), deps=("T-9",))

    ops.ask(cfg, "T-1", "Pick up T-1 — OK?", qid="q1")
    event_log.append(home, "T-1", "QuestionAnswered", {"qid": "q1", "answer": "ok"}, actor="human")
    ops.set_phase(cfg, "T-1", Phase.READY, reason="approved: ok")
    ops.set_phase(cfg, "T-1", Phase.IMPLEMENTING, reason="worktree ready")
    ops.fail(cfg, "T-1", "pytest red: test_widget failed")
    # CiObserved / ImplStepRecorded are appended raw (as the skill does via
    # `maestro append`), bypassing ops._append — the dossier still picks them
    # up on the next ops call because the fold reads the whole log fresh.
    event_log.append(home, "T-1", "CiObserved", {"state": "passing"}, actor="reconciler")
    event_log.append(home, "T-1", "ImplStepRecorded",
                     {"turn": 1, "role": "Implementer", "kind": "edit", "tool": "Edit",
                      "summary": "maestro/widget.py"}, actor="reconciler")
    ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green")

    path = context.context_path(home, "T-1")
    assert path.exists()
    text = path.read_text(encoding="utf-8")

    assert "GENERATED by maestro" in text
    assert "# Context: T-1 — Widget" in text
    # Phase history: verbatim reasons
    assert "approved: ok" in text
    assert "worktree ready" in text
    assert "tests green" in text
    # Answered questions: verbatim Q + A
    assert "Pick up T-1 — OK?" in text
    assert "ok" in text
    # Failures
    assert "pytest red: test_widget failed" in text
    # CI observations
    assert "passing" in text
    # Impl steps
    assert "maestro/widget.py" in text
    # Dependencies + their phase
    assert "T-9: done" in text


def test_dossier_reflects_missing_dependency_gracefully(cfg):
    """A dependsOn key with no ticket yet still renders (default snapshot phase)."""
    _create(cfg, "T-1", deps=("T-404",))
    ops.observe_spec(cfg, "T-1")

    text = context.context_path(cfg.home, "T-1").read_text(encoding="utf-8")
    assert "T-404: triaging" in text


# ---------------------------------------------------------------------------
# Determinism: same log folds to byte-identical output
# ---------------------------------------------------------------------------

def test_render_is_byte_identical_for_the_same_events(cfg):
    _create(cfg, "T-1", acs=("do the thing",))
    ops.ask(cfg, "T-1", "OK?", qid="q1")
    event_log.append(cfg.home, "T-1", "QuestionAnswered", {"qid": "q1", "answer": "yes"}, actor="human")
    ops.set_phase(cfg, "T-1", Phase.READY, reason="approved: yes")

    events = event_log.read(cfg.home, "T-1")
    first = context.render("T-1", "Test ticket", events, {"T-9": "done"})
    second = context.render("T-1", "Test ticket", events, {"T-9": "done"})

    assert first == second


def test_render_output_is_stable_across_regenerate_calls(cfg):
    _create(cfg, "T-1")
    ops.set_phase(cfg, "T-1", Phase.READY, reason="approved: ok")

    path = context.context_path(cfg.home, "T-1")
    first = path.read_text(encoding="utf-8")
    context.regenerate(cfg.home, "T-1")  # no new events since
    second = path.read_text(encoding="utf-8")

    assert first == second


# ---------------------------------------------------------------------------
# Token-bounded per-section caps
# ---------------------------------------------------------------------------

def test_dossier_caps_phase_history_and_notes_the_omission(cfg):
    _create(cfg, "T-1")
    # Ping-pong past the cap so there are more phase changes than MAX_PHASE_CHANGES.
    total = context.MAX_PHASE_CHANGES + 5
    for i in range(total):
        dst = Phase.IMPLEMENTING if i % 2 == 0 else Phase.AWAITING_CI
        ops.set_phase(cfg, "T-1", dst, reason=f"iteration {i}")

    text = context.context_path(cfg.home, "T-1").read_text(encoding="utf-8")
    assert "earlier phase change(s) omitted" in text
    assert "iteration 0" not in text  # oldest dropped
    assert f"iteration {total - 1}" in text  # newest kept


# ---------------------------------------------------------------------------
# AcVerified event + verify-ac verb
# ---------------------------------------------------------------------------

def test_verify_ac_appends_event_and_reduces_unverified_count(cfg):
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget", "document it"))
    snap = snap_mod.load(home, "T-1")
    spec_text = store.spec_path(home, "T-1").read_text(encoding="utf-8")
    assert snap.acs_unverified(spec_text) == 2

    h = ops.verify_ac(cfg, "T-1", 1, "tests/test_widget.py::test_builds passes")
    snap = snap_mod.load(home, "T-1")
    assert snap.ac_verified[h] == "tests/test_widget.py::test_builds passes"
    assert snap.acs_unverified(spec_text) == 1

    ops.verify_ac(cfg, "T-1", 2, "README.md updated with widget docs")
    snap = snap_mod.load(home, "T-1")
    assert snap.acs_unverified(spec_text) == 0


def test_verify_ac_via_real_cli(cfg):
    """CLI-driven, per the QA convention: exercise the actual `maestro` surface."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))

    rc = cli.main(["--home", str(home), "verify-ac", "T-1", "--ac", "1",
                   "--evidence", "ran pytest, green"])
    assert rc == 0

    events = event_log.read(home, "T-1")
    ac_events = [e for e in events if e["type"] == "AcVerified"]
    assert len(ac_events) == 1
    assert ac_events[0]["payload"]["evidence"] == "ran pytest, green"
    assert ac_events[0]["payload"]["ac_index"] == 1


def test_verify_ac_is_idempotent_by_step_id(cfg):
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, "first evidence")
    ops.verify_ac(cfg, "T-1", 1, "second evidence — should be a no-op")

    events = event_log.read(cfg.home, "T-1")
    ac_events = [e for e in events if e["type"] == "AcVerified"]
    assert len(ac_events) == 1
    assert ac_events[0]["payload"]["evidence"] == "first evidence"


def test_verify_ac_out_of_range_raises(cfg):
    _create(cfg, "T-1", acs=("only one thing",))
    with pytest.raises(store.MaestroError, match="out of range"):
        ops.verify_ac(cfg, "T-1", 2, "n/a")


def test_spec_edit_desyncs_stale_attestation(cfg):
    """A human edit to an AC's line invalidates its old attestation by content
    hash — proving desync detection instead of a stale/mismatched index match."""
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, "verified against the original wording")

    spec_text = store.spec_path(home, "T-1").read_text(encoding="utf-8")
    snap = snap_mod.load(home, "T-1")
    assert snap.acs_unverified(spec_text) == 0

    # Human edits the AC's wording (still AC #1, but different content hash).
    _write_spec(home, "T-1", acs=("build the widget with a handle",))
    new_spec_text = store.spec_path(home, "T-1").read_text(encoding="utf-8")

    snap = snap_mod.load(home, "T-1")  # unchanged event log
    assert snap.acs_unverified(new_spec_text) == 1  # the stale attestation no longer counts


# ---------------------------------------------------------------------------
# Soft-warn at set-phase awaiting-ci
# ---------------------------------------------------------------------------

def test_set_phase_awaiting_ci_soft_warns_when_acs_unverified(cfg):
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget", "document it"))

    ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green")

    events = event_log.read(home, "T-1")
    notes = [e for e in events if e["type"] == "Note" and "unverified" in e["payload"].get("text", "")]
    assert len(notes) == 1
    assert "2 acceptance criteria unverified" in notes[0]["payload"]["text"]
    # Soft-warn only — the phase transition itself still happened.
    assert snap_mod.load(home, "T-1").phase == Phase.AWAITING_CI.value


def test_set_phase_awaiting_ci_no_warn_once_all_acs_verified(cfg):
    home = cfg.home
    _create(cfg, "T-1", acs=("build the widget",))
    ops.verify_ac(cfg, "T-1", 1, "evidence")

    ops.set_phase(cfg, "T-1", Phase.AWAITING_CI, reason="tests green")

    events = event_log.read(home, "T-1")
    notes = [e for e in events if e["type"] == "Note" and "unverified" in e["payload"].get("text", "")]
    assert notes == []
