"""Interactive TUI for maestro — requires the `tui` extra (textual).

Package layout: `app.py` (MaestroTUI + entrypoint), `screens.py` (full-screen
views), `modals.py` (input dialogs), `render.py` (pure markup helpers),
`detail.py` / `events.py` (textual-free renderers). Everything external —
cli.py and the tests — imports through this namespace, so internal layout can
change without breaking importers.
"""
from .app import MaestroTUI, main, _FILTERS, _NEEDS_YOU_PHASES
from .modals import (
    _ACCEPT_ALL,
    _ActionMenu,
    MenuRow,
    menu_actions,
    _AcEvidenceModal,
    _AddAcModal,
    _AnswerModal,
    _CmdModal,
    _ConfirmModal,
    _CreateModal,
    _DEFAULT_COMMANDS,
    HoldModal,
    _EventPayloadModal,
    _ImportLinearModal,
    _DirectionModal,
    _InboxModal,
    _IntervalModal,
    _PauseModal,
    _PHASE_COMMANDS,
    _RunnerModal,
    _ScheduleModal,
    _SuggestAcsModal,
    _TicketPickModal,
)
from .render import (
    _PHASE_STYLE,
    _fmt_age,
    _fmt_epoch,
    _render_badge,
    _render_env,
    _render_fleet,
    _styled_row,
)
from .screens import (
    ActivityScreen,
    AcScreen,
    BackupsScreen,
    DecisionsScreen,
    DetailScreen,
    EnvScreen,
    EventsScreen,
    DepsScreen,
    FleetScreen,
    InboxScreen,
    LogsScreen,
    ProposalScreen,
    ReviewScreen,
    ScheduleScreen,
    SpecScreen,
    WhyScreen,
)

__all__ = [
    "MenuRow",
    "_ActionMenu",
    "menu_actions",
    "AcScreen",
    "WhyScreen",
    "MaestroTUI",
    "main",
    "ActivityScreen",
    "BackupsScreen",
    "DecisionsScreen",
    "DetailScreen",
    "EnvScreen",
    "EventsScreen",
    "DepsScreen",
    "FleetScreen",
    "InboxScreen",
    "LogsScreen",
    "ProposalScreen",
    "ReviewScreen",
    "ScheduleScreen",
    "SpecScreen",
    "_ACCEPT_ALL",
    "_AcEvidenceModal",
    "_AddAcModal",
    "_AnswerModal",
    "_CmdModal",
    "_ConfirmModal",
    "_CreateModal",
    "_ImportLinearModal",
    "_DirectionModal",
    "_InboxModal",
    "_IntervalModal",
    "_PauseModal",
    "HoldModal",
    "_RunnerModal",
    "_ScheduleModal",
    "_SuggestAcsModal",
    "_TicketPickModal",
    "_DEFAULT_COMMANDS",
    "_EventPayloadModal",
    "_PHASE_COMMANDS",
    "_FILTERS",
    "_NEEDS_YOU_PHASES",
    "_PHASE_STYLE",
    "_fmt_age",
    "_fmt_epoch",
    "_render_badge",
    "_render_env",
    "_render_fleet",
    "_styled_row",
]
